// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkWquvWKZKPc6bmS-HBvn_zC-SJgnvkMY',
    appId: '1:47749609188:web:8f607cfea1a0edfc0adef1',
    messagingSenderId: '47749609188',
    projectId: 'balanced-meal-414be',
    authDomain: 'balanced-meal-414be.firebaseapp.com',
    storageBucket: 'balanced-meal-414be.firebasestorage.app',
    measurementId: 'G-VWGDHXJQG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl01-Z-lC1SR8is2y2jFB4a1gEthroPog',
    appId: '1:47749609188:android:4035bda3f5e0999a0adef1',
    messagingSenderId: '47749609188',
    projectId: 'balanced-meal-414be',
    storageBucket: 'balanced-meal-414be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD0Y6eryrFa-eCKysMeu3EiVJuSZ-FveU',
    appId: '1:47749609188:ios:f3bbc43e74dafd1d0adef1',
    messagingSenderId: '47749609188',
    projectId: 'balanced-meal-414be',
    storageBucket: 'balanced-meal-414be.firebasestorage.app',
    iosBundleId: 'com.example.balancedMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD0Y6eryrFa-eCKysMeu3EiVJuSZ-FveU',
    appId: '1:47749609188:ios:f3bbc43e74dafd1d0adef1',
    messagingSenderId: '47749609188',
    projectId: 'balanced-meal-414be',
    storageBucket: 'balanced-meal-414be.firebasestorage.app',
    iosBundleId: 'com.example.balancedMeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkWquvWKZKPc6bmS-HBvn_zC-SJgnvkMY',
    appId: '1:47749609188:web:0a0be2fe4fe9f64a0adef1',
    messagingSenderId: '47749609188',
    projectId: 'balanced-meal-414be',
    authDomain: 'balanced-meal-414be.firebaseapp.com',
    storageBucket: 'balanced-meal-414be.firebasestorage.app',
    measurementId: 'G-PG6551R3NE',
  );
}
